In [1]:
import numpy as np

In [2]:
print(list(range(10)))
print(np.arange(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
l = [1,2,3]
print(l*3)
np_l = np.array(l)
print(np_l*3)
# element wise multiplication
print()

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]



## Basics related to dimensions and size

In [ ]:
a = np.array([[1,2,3],[4,5,6]])

# tells the no. of dimensions
print(a.ndim)

# get shape
print(a.shape) # returns a tuple

# to know the data type
print(a.dtype)

In [11]:
# we can specify datatype while creating array
a = np.array([[1,2,3],[4,5,6]], dtype='int16')
print(a.dtype)

int16


In [14]:
# to get total no. of elements
a.size

6

## Accessing and changing elements

In [21]:
a = np.array([[1,2,3],[4,5,6]])

# accessing an elememnt
print(a[1][1],a[1][-1])

# accessing a row
print(a[1,:],a[-2])

# accessing a column
print(a[:,1],a[:,-1])

5 6
[4 5 6] [1 2 3]
[2 5] [3 6]


In [26]:
# Changing a single element
a[1][2] = 8
print(a)

#changing whole row value
a[1,:] = 8
print(a)

# chaning a column value
a[:,1] = 5
print(a)

[[1 2 3]
 [8 8 8]]
[[1 2 3]
 [8 8 8]]
[[1 5 3]
 [8 5 8]]


## Initializaton of np arrays

In [56]:
# initialize with 0s
b = np.zeros(5)
print(b)
b = np.zeros((2,3), dtype= 'int32')
print(b)

# initialise with 1s
b = np.ones(a.shape)
print(b)

#initialise with a constant
b = np.full((3,3),4)
print(b)

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [42]:
# Random nos. initialisation

# 0 to 1 float nos
b = np.random.rand(4,2)
print(b)

#integers from 0 to 9
b = np.random.randint(10, size=(4,2))
print(b)

#integers from 5 to 9
b = np.random.randint(5,10, size=(4,2))
print(b)

[[0.35787022 0.1284036 ]
 [0.08124125 0.2084589 ]
 [0.76598247 0.06473207]
 [0.83146664 0.66443363]]
[[7 7]
 [6 2]
 [0 7]
 [4 0]]
[[6 8]
 [5 9]
 [6 7]
 [7 8]]


In [48]:
b = np.identity(3)
print(b)

b = np.arange(10)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 1 2 3 4 5 6 7 8 9]


In [45]:
# [[1,1,1,1,1]
# [1,0,0,0,1]
# [1,0,9,0,1]
# [1,0,0,0,1]
# [1,1,1,1,1]] Construct this matrix

ans = np.ones((5,5))
ans[1:4,1:4] = np.zeros((3,3))
ans[2][2] = 9
print(ans)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Mathematics wiht np arrays

In [49]:
a = np.arange(10)
a+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
a/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [51]:
a%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [52]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [53]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

## Algebra

In [63]:
# Trnspose of matrix
b = np.full((3,2),2)
print(b)
print(np.transpose(b))

[[2 2]
 [2 2]
 [2 2]]
[[2 2 2]
 [2 2 2]]


In [62]:
# Matrix multiplication
a = np.ones((3,3))
print(a)
print(b)
print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]
 [6. 6.]]


In [69]:
# Determinant of a matrix
a = np.identity(3)*2
print(a,np.linalg.det(a))

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]] 7.999999999999998


In [ ]:
# https://docs.scipy.org/doc/numpy/reference/routines.linalg.html
# More matrix operations
# inverse, singular vector decomposition, Eigenvalues, Trace etc.

## Statistics

In [3]:
s = [np.arange(1,5),np.arange(5,9)]
print(s)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [4]:
# min and max using axis
print(np.min(s))
print(np.min(s,axis=0))
print(np.max(s,axis=1))

1
[1 2 3 4]
[4 8]


In [10]:
# sum and mean
print(np.sum(s,axis=0))
print(np.mean(s,axis=1))

[ 6  8 10 12]
[2.5 6.5]


## Reorganizing arrays

In [14]:
# reshaping
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [17]:
# combining(stacking) 2 arrays vertically and horizontally
a1 = np.ones((2,2))
a2 = np.zeros((2,2))
print(np.hstack((a1,a2)))
print(np.vstack((a1,a2)))

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]


## Loading data from file

In [2]:
filedata = np.genfromtxt('data.txt',delimiter=',', dtype='int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [12]:
#Boolean masking
print(filedata > 50)
print()

# Using boolean masking as index
print(filedata[filedata > 50])

#using list of indices
a = np.arange(10,20)
print(a[[1,5,8]])

[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]

[196  75 766  75  55 999  78  76  88]
[11 15 18]


In [13]:
# Questions related to indexing on given array
a = np.arange(1,31).reshape((6,5))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [14]:
a[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [25]:
a[np.arange(4),np.arange(1,5)]

array([ 2,  8, 14, 20])

In [26]:
a[[0,4,5],3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])